name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    branches: [ "master" ]
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  build:

    #runs-on: ubuntu-latest
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: mkdir bld_ && cd bld_ && cmake ../
    - name: make
      run: make -j4
